### ISSUE TITLE
rename to cyberark-conjur

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur-puppet#10]
The module name is `conjur-conjur` right now. But to be consistent with source and our other integrations it should be `cyberark-conjur`.

Steps to success:
0. Wait until we have Puppet Forge 'cyberark' user creds
1. Rename `conjur-conjur` -> `cyberark-conjur` in this project.
2. Re-publish latest release to `cyberark-conjur` on the Forge.
3. If possible, put a deprecation notice on the `conjur-conjur` forge page.
4. Talk to Puppet about being re-certified.

**Comment by dustinmm80** [comment]
@Daniel-Warner-X as we talked about

**Comment by dividedmind** [comment]
I think we should probably contact Puppet for tips on how to accomplish this in the smoothest way possible. Ideally `conjur-conjur` would redirect to `cyberark-conjur`, but this will probably need their help.

**Comment by ryanprior** [comment]
This is done (https://forge.puppet.com/cyberark/conjur), closing.
