### ISSUE TITLE
The automated tests for this Puppet module with Linux agents are expanded

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#101]
The following test flows are verified in the project's automated test suite:

## Puppet 5
- [ ] Conjur identity via host factory, Ubuntu agents, Conjur OSS
- [ ] Conjur identity via host / API key with configuration stored in identity files, Alpine agents, DAP

## Puppet 6
- [ ] Conjur identity via host / API key hardcoded in manifest, Alpine agents, DAP
- [ ] Conjur identity via host / API key with configuration stored in identity files, Ubuntu agents, Conjur OSS
- [ ] Conjur identity via host factory, Alpine agents, Conjur OSS
- [ ] Conjur identity via host factory, Ubuntu agents, DAP

If it's easier to test more cases, we can - but this set is the minimally required set.

In all tests, we are validating that for the Puppet module configured as specified that it is able to correctly authenticate to Conjur, retrieve secret values, and make them available on the given Puppet agent.

**Comment by izgeri** [comment]
Note: this set was generated using [web PICT](http://amibugshare.com/pict/) with the following input:
```
Identity: Host factory, Host/API key
Config: Hardcoded, Identity files
OS Version: Alpine, Ubuntu
Conjur Version: OSS, DAP
Puppet version: Puppet 5, Puppet 6

IF [Identity] = "Host factory" THEN [Config] = "Hardcoded";
```

**Comment by sgnn7** [comment]
Wider E2E tests were included though DAP testing was not done as part of this effort
