### ISSUE TITLE
Puppet module has an open source acknowledgements file

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#103]
AC:
- [ ] There is an OSS acknowledgements file that details the OSS dependencies included in the module and their licenses / copyrights
- [ ] The CONTRIBUTING release instructions include guidance on reviewing and updating the OSS acknowledgements

**Comment by sgnn7** [comment]
Released with [v3.0.0rc3](https://forge.puppet.com/cyberark/conjur). Closing.
