### ISSUE TITLE
Add complete support for `cert_file`

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#105]
## Is your feature request related to a problem? Please describe.

`cert_file` is a much better way to define the ssl certificate value

## Describe the solution you would like

- [ ] `cert_file` is supported and documented on all platforms for all use paths

## Describe alternatives you have considered

N/A

## Additional context

This seems like a decent way to provide a conf file cert value so we should have it documented for sure.

**Comment by izgeri** [comment]
@sgnn7 maybe this issue should become "add complete support for `cert_file`"?

**Comment by sgnn7** [comment]
@izgeri makes sense. Updated the title and description for the post-deferred work needed.

**Comment by sgnn7** [comment]
Moving to M4
