### ISSUE TITLE
Add support for `cert_file` on Windows

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#113]
## Summary

`cert_file` configuration parameter does not work on Windows environments. Neither facter nor HFT-config `manufacture_host` try to use this parameter, meaning that you must provision Windows machines with string-based `ssl_certifcate` in configuration which is in some situation much harder to automate.

Dev info:
- [*nix automatically converts `cert_file` to `ssl_certifcate`](https://github.com/cyberark/conjur-puppet/blob/6f13d59/lib/conjur/puppet_module/config.rb#L17-L18)
- [Windows facter doesn't do the same](https://github.com/cyberark/conjur-puppet/blob/6f13d59/lib/conjur/puppet_module/config.rb#L25-L35)
- [Windows HFT host creation doesn't either](https://github.com/cyberark/conjur-puppet/blob/6f13d59c8f449d6bf0be75feefcccab0754a4ecc/manifests/init.pp#L4-L13) (this is used by `manufacture_host`)

## Steps to Reproduce

1. Setup puppet with a clean Windows host ready (don't run agent yet)
2. Setup conjur HFTs
3. Configure all relevant Conjur facts but place the Conjur CA cert on the machine and use `cert_path` instead of `ssl_certificate`
4. Run the agent on the node

## Expected Results
Agent can pull secrets

## Actual Results (including error logs, if applicable)
Agent run fails with errors as the conjur `ssl_certificate` is undefined

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

Tested on Puppet 6 and pre-3.0.0 version but this error would be visible on puppet 5 and any older version as well probably.

## Environment setup

Puppet Master: Docker-compose, v6
Puppet Agent: Windows 2012r2 VM in VirtualBox
Conjur Master: Docker-compose, v5

## Additional Information

N/A

**Comment by izgeri** [comment]
@sgnn7 as part of fixing this, will the README also be updated to demonstrate how to configure the cert when using a Windows agent?

**Comment by sgnn7** [comment]
Absolutely - currently the docs are already missing information about this variable in the README but that's only for the *nix platform.

**Comment by sgnn7** [comment]
Hmm I don't remember manually closing this issue... Good catch!
