### ISSUE TITLE
Error logging improvements

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#114]
## Summary

Currently, if there is an error within the module, the error output is not always enough to figure out what went wrong as only the error message line is printed and then silently eaten in facter, making it hard to debug issues.

Dev info:
- [Error handling spot](https://github.com/cyberark/conjur-puppet/blob/6f13d59c8f449d6bf0be75feefcccab0754a4ecc/lib/facter/conjur.rb#L104-L107)
- Change of the error line to this fixes majority of the UX:
```diff
-      warn $!                                    
+      warn "Conjur token retrieval failure: " + $!.full_message(highlight: true, order: :top)
```

## Steps to Reproduce

1. Setup puppet with a clean Windows host ready (don't run agent yet)
2. Setup conjur HFTs
3. Configure all relevant Conjur facts but leave one out
4. Run the agent on the node

## Expected Results
Well formed and descriptive errors

## Actual Results (including error logs, if applicable)
Often obscure one-line error messages

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

Tested on Puppet 6 and pre-3.0.0 version but this error would be visible on puppet 5 and any older version as well probably.

## Environment setup

Puppet Master: Docker-compose, v6
Puppet Agent: Windows 2012r2 VM in VirtualBox
Conjur Master: Docker-compose, v5

## Additional Information

N/A

**Comment by izgeri** [comment]
One thing we want to make sure we understand is the UX when someone invokes `conjur::secret` but doesn't wrap it with `Deferred` - we don't support this flow, so there should be a clear error to help the user recover from this.

**Comment by sgnn7** [comment]
Original issue is no longer valid as we do not use Facter anymore. I'll split out the other issue (skipping `Deferred` UX) into its own issue though. Closing.
