### ISSUE TITLE
Functionality that pulls the Conjur configuration from Windows registry / WinCred should be migrated to the Conjur Ruby client

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#116]
At current, the Conjur Puppet module supports a few ways of providing Conjur with its configuration:
- Hardcoded in the manifest (consistent with other integrations and with standard Ruby client instantiation)
- Written to config files (also a supported method for Conjur clients)
- Written to Windows registry / WinCred

The third method _should_ be supported by the Ruby client and leveraged by this module, rather than being implemented and fully tested as part of this module. In this card, the functionality should be migrated to the Ruby client and the Puppet module should be updated to invoke the new version of the Ruby client that includes this functionality. The tests around this flow can largely move to the Ruby client as well, and the integration tests here can validate a subset of the flows work end-to-end.

**Note**: Given the amount of work required to do this, it is a small epic, not a single task.

**Comment by sgnn7** [comment]
This won't be possible - we cannot use a third-party gem in this way as a dependency of a puppet module. As far as I can tell, only other modules can be used as dependencies so I'll close this issue unless I hear otherwise.

**Comment by izgeri** [comment]
😞 bummer. would be nice to use our Ruby lib here, for example.
