### ISSUE TITLE
Puppet integration has troubleshooting documentation

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#120]
Add a `Troubleshooting` section to the README.

Each troubleshooting example can use the same sort of template that [Secretless uses](https://github.com/cyberark/secretless-broker/wiki/Troubleshooting-Guide#template-for-adding-new-troubleshooting-scenarios)

**Comment by sgnn7** [comment]
Some troubleshooting info has been collected here: https://github.com/cyberark/conjur-puppet/issues/192

**Comment by sgnn7** [comment]
Additional case we should cover:
```puppet
Sensitive(Deferred(conjur::secret('<id>')))
```

Which will result also in a 500 error since it resolves on the server

**Comment by sgnn7** [comment]
```
Might help to have some troubleshooting hints:
Use '--trace' and '--verbose' when running puppet agent to get verbose output with traces, e.g.
`sudo /opt/puppetlabs/bin/puppet agent --trace --verbose --test'
Use 'systemctl status puppetserver' to check server status on a Linux host
Use 'journalctl -xe' to get puppetserver logs on a Linux host
```
