### ISSUE TITLE
Repo has static analysis as part of its pipeline

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#121]
AC:
- [x] Static analysis (code coverage, linting, etc.) has been added to pipeline
- [x] Issues flagged by static analysis have been resolved

**Comment by sgnn7** [comment]
Per @andytinkham , we may also need this:
```
sh 'cp coverage/coverage.xml cobertura.xml'
ccCoverage("cobertura", "github.com/cyberark/conjur-puppet")
```

**Comment by sgnn7** [comment]
This story has been resolved with `pdk validate` that runs on every build and inclusion of cobertura code coverage reporting in Jenkins. All issues with linting have been resolved that were found. Leftovers (pushing coverage to CC) is in #53 so we can close this issue now.
