### ISSUE TITLE
Support Windows Nodes

### ISSUE THREAD

**Issue by 1WindowsPuppetAdmin** [cyberark/conjur-puppet#14]
This module should support windows nodes. We need passwords too. :)

**Comment by jvanderhoof** [comment]
@1WindowsPuppetAdmin: we've got two stories bring some Windows love to the module:
- #21 
- #22 
This will add Windows support for enrolling nodes and delivering credentials.

**Comment by dividedmind** [comment]
Closing as duplicate of #24.
