### ISSUE TITLE
Include warning that stand-alone Puppet (Puppet Apply) does not provide encryption

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-puppet#145]
## Is your feature request related to a problem? Please describe.

When Puppet is used in [stand-alone mode](https://puppet.com/docs/puppet/5.5/architecture.html#the-stand-alone-architecture) (i.e. the [`puppet apply ...`](https://puppet.com/docs/puppet/5.5/man/apply.html) command is used on the Puppet agent), the setup will not necessarily include HTTPS encryption between the Puppet agent and Conjur.

## Describe the solution you would like

A warning is included in the README.md file that using Puppet in [stand-alone mode](https://puppet.com/docs/puppet/5.5/architecture.html#the-stand-alone-architecture) mode, the connection from Puppet agent to Conjur may not necessarily include HTTPS encryption.

**Comment by sgnn7** [comment]
This ticket is no longer valid as it applied only to old code. Closing.
