### ISSUE TITLE
When using Puppet server-side credentials, specifying both `cert_file` and `ssl_certificate` errors out on Windows

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#147]
## Steps to Reproduce
1. Create puppet server and conjur master
2. Configure puppet server to provide server-side credentials to a Windows node. Specify
  both `cert_file` and `ssl_certificate` parameters.
3. Run agent on that Windows node

## Expected Results

No errors

## Actual Results (including error logs, if applicable)

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Cannot reassign variable '$ssl_certificate' (file: /etc/puppetlabs/code/environments/production/modules/conjur/manifests/init.pp, line: 15, column: 22) on node windows2016.us.cyber-ark.com
```

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
v2.0.3 @ [this](https://github.com/cyberark/conjur-puppet/commit/342b097f69d4397f5f886caad7715c70157b47c2)

## Environment setup

Vagrant setup, Windows 2016, hardcoded class manifest details.

## Additional Information

The bug makes sense since Puppet DSL apparently [doesn't allow re-assignment](https://ask.puppet.com/question/13242/cannot-reassign-variable/)
but we do it [here](https://github.com/cyberark/conjur-puppet/blob/master/manifests/init.pp#L15).

**Comment by izgeri** [comment]
it would be good to be clear about which value it uses in the case both are specified, too (I think this is clear in the README, no?)

**Comment by sgnn7** [comment]
Yeah the docs specify that cert_file has precedence in almost all cases

**Comment by sgnn7** [comment]
This bug is no longer valid as the new changes do not have the problematic code. All other `cert_file` functionality support is moved to issue #105. Closing.
