### ISSUE TITLE
Improve README in regards to `cert_file` parameter

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#148]
## Is your feature request related to a problem? Please describe.

Currently in our README:
- We don't specify where the file will be read from (server or agent?)
- For server-specific locations, we should use only *nix paths examples but we use *nix paths
- Windows path examples _must_ be regular windows paths (`C:\foo\bar.pem`) and not *nix-y ones (`/foo/bar.pem`)
- Some examples use `cert_file => file('...')` pattern which is not correct

## Describe the solution you would like

- [ ] All use of `cert_file`s in README should specify which node this file will be pulled from
- [ ] All server-side `cert_file` README examples should use *nix paths
- [ ] Windows `cert_file` README examples use regular windows fully-qualified paths
- [ ] All uses of `cert_file` in README examples only set this variable to a path string and not the content function (`file()`)

## Describe alternatives you have considered

N/A

## Additional context

Add any other context information about the feature request here.

**Comment by doodlesbykumbi** [comment]
@sgnn7 `cert_file` is always on *nix paths. It is only the Windows Registry value named `CertFile` that reads from Windows

**Comment by sgnn7** [comment]
@doodlesbykumbi good catch! I was writing this while trying to remember the issues w/ it from very terse notes :/
