### ISSUE TITLE
Puppet 6 compatibility

### ISSUE THREAD

**Issue by Wernervdmerwe** [cyberark/conjur-puppet#15]
The metadata file pin this module to <5, Puppet is now in version 6, can this be updated?

**Comment by jvanderhoof** [comment]
@Wernervdmerwe: We're about to kick off an effort to leverage Deferred Types (#13).  I know this goes well beyond the ask here, but that work should resolve this issue.

**Comment by turbodog** [comment]
Seconding the request to indicate Puppet 6 compatibility. Open Source is up to version 6.4 now and this also ships in current Puppet Enterprise 2019.x.

**Comment by jvanderhoof** [comment]
@turbodog, we're very close to a new release which brings Windows support.  We're in the process of adding integration tests using Puppet 6.  We'll get this resolved soon.

**Comment by turbodog** [comment]
Awesome!

**Comment by dividedmind** [comment]
Closing this as duplicate of #20 .
