### ISSUE TITLE
Check that Windows Registry entries created by puppet module are read-only for non-admins

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-puppet#154]
## Is your feature request related to a problem? Please describe.

During the review for PR #146, one question that came up was whether the Conjur Puppet module sets the proper Read-Only permissions for general, non-administrative users when it automatically creates Windows Registry entries for Conjur connection information.

## Describe the solution you would like

Confirm whether or not Conjur Puppet module is creating Windows Registry entries with the proper Read-Only permissions for non-administrative users. If not, create a PR to modify this.

**Comment by sgnn7** [comment]
We no longer create registry entries from within our puppet module so this issue is invalid as described. Closing.
