### ISSUE TITLE
cert_file param on conjur class errors when attempting to reassign ssl_certificate

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/conjur-puppet#156]
## Summary
Using the `cert_file` param on the conjur class (which only happens on the server) errors when attempting to reassign ssl_certificate. The module tries to reassign the `ssl_certificate` variable with the contents read from `cert_file`. Puppet variables are immutable once set, and so an error is thrown.

Note that if you use just `ssl_certificate` param it works since the logic above is circumvented

## Steps to Reproduce
1. Run a puppet agent using the `cert_file` parameter on the server (Hiera or hardcoded conjur class in the manifest)

## Expected Results

`cert_file` should be used as the source of the SSL certificate for Conjur

## Actual Results (including error logs, if applicable)

The puppet agent run errors with:
```
Unfortunately I got an error when using cert_file :disappointed: 
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Cannot reassign variable '$ssl_certificate' (file: /etc/puppetlabs/code/environments/production/modules/conjur/manifests/init.pp, line: 15, column: 22) on node 7c0b1985e297
```

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

Unreleased commit on master at the moment of creation of this issue.

## Environment setup
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
Which cloud provider? Which container orchestrator (including version)? 
The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

+ Agent v5 on Windows Server 2019 (Windows container on a Windows VM in EC2)
+ Server v5 (In a container as a docker-compose service)

**Comment by doodlesbykumbi** [comment]
Reopened since the PR was reverted https://github.com/cyberark/conjur-puppet/pull/158

**Comment by sgnn7** [comment]
Code that caused this issue is no longer present in main branch. Closing.
