### ISSUE TITLE
There is a new release of the Puppet module that includes preliminary support for Puppet 6 with Linux agents

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#163]
AC:
- [x] There is a new tag with preliminary support for Linux agents
- [x] The change log is updated as below
- [x] The metadata is updated as below
- [x] Puppet v6 support is added to the metadata, and a "Community level support" caveat is added to the README
- [x] Once a tag has been added, a `v2` branch is created off of the tag to maintain the v2 functionality in a separate branch
- [x] Post-release, the README is updated to point users to v2.x of the module / the `v2` branch if they need Conjur Enterprise v4 support

## Change log updates

The change log for this version should include:
```
### Added
- Preliminary support for Puppet 6 with Linux agents. [Epic cyberark/conjur-puppet#20](https://github.com/cyberark/conjur-puppet/issues/20)

### Deprecated
- Support for using the Conjur Puppet module with Conjur Enterprise v4 is now deprecated. Support
  will be removed in the next major release. The `conjurize` method of providing the Conjur Puppet module
  with its Conjur identity will also no longer be supported as of the next version.
- Support for using the Conjur Puppet module with [Windows Server 2008](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%20Server%202008) or [Debian 7](https://wiki.debian.org/DebianWheezy) agents, since both operating systems have now reached end of life.
```

## Metadata updates
- Remove Windows Server 2008
- Remove Debian 7
- Add Debian 9, 10
- Add Ubuntu 18.04 (we now test against this version)
- Add Ubuntu 20.04
- Add Alpine 3.9 (we now test against this version)

Which leaves us with the following supported OSes:
- Windows Server 2012 R2, 2016, 2019
- Ubuntu 14.04, 16.04, 18.04, 20.04
- Centos 6, 7
- Debian 8, 9, 10
- Alpine 3.9

In addition, we should:
- Add support for Puppet 6 (this will need to be paired with at least a README caveat in the "System Requirements" section that Puppet 6 support is [Community Level](https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md#community))
- Change "author" to "CyberArk Software, Inc."
- Consider adding "tags" - An array of four to six key words to help people find your module (e.g. `["msyql", "database", "monitoring", "reporting"]`)

**Comment by sgnn7** [comment]
All items completed. Moving to Closed column.
