### ISSUE TITLE
Generate reference documentation using Puppet Strings

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#166]
[Puppet strings](https://puppet.com/docs/puppet/5.5/puppet_strings.html) can be used to automatically generic REFERENCE.md documentation based on specially formatted comments of Puppet classes, types, and resources.

In this card, we'll migrate the existing REFERENCE content to comments so that it can be generated using Puppet strings, and going forward the code comments can be maintained and used to auto update the REFERENCE file.

AC:
- [ ] REFERENCE.md is generated by code comments using `puppet strings`

**Comment by izgeri** [comment]
@sgnn7 I think this issue is done already, right? I see `gen_docs.sh` is using `puppet strings`

**Comment by sgnn7** [comment]
Not quite - I was having some issues running this command with the bleeding-edge PDK and I want to ensure this still works. There's also a question if we want this documentation to be generated on-the-fly during releases and be excluded from the repo by default.

**Comment by sgnn7** [comment]
Closed via https://github.com/cyberark/conjur-puppet/pull/225.
