### ISSUE TITLE
Deprecate Puppet 5, HFTs

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#180]
We've decided to deprecate support for Puppet 5 and Host Factory Tokens in the v3.0 release of our module, so we need to announce deprecation in the 2.x stream.

- [x] Add a commit in the `v2` branch that announces deprecation for Puppet 5 and HFTs (ensure PO reviews)
- [x] Add a tag in the `v2` branch to publish the additional deprecations to Puppet Forge
- [x] Cherry-pick the deprecation commit to the master branch

**Comment by sgnn7** [comment]
All tasks on this issue are now complete. Closing.
