### ISSUE TITLE
`conjur` class establishes identity for Windows servers

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-puppet#21]
As a Windows admin, I want to utilized the module to enroll a Windows node in Conjur, so that I can automate the enrollment of Windows servers just like I can do for Linux servers.

GIVEN a Puppet master, a un-configured Windows node, Conjur, and a manifest which utilizes the host factory token or the host API key
WHEN I run the manifest
THEN the node is enrolled into the correct Conjur layer (when using the host factory token)
AND the node has credentials which can be used to connect to Conjur

**Comment by dividedmind** [comment]
One additional problem here is we've never supported Windows boxes in the earnest so we don't have an established practice of where to keep that identity. I wonder if it should be one of the outcomes of this work, or is it better to open another ticket (maybe at conjur-cli or conjur-api repository) which would be a prerequisite for this.
