### ISSUE TITLE
There is a blog post on the 3.0.0 release of the Conjur Puppet module

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#217]
The blog post should cover
- What's new in 3.0.0
  - Support for deferred actions
  - Support for compile masters
  - Deprecated support
- How to migrate from v2 to v3
  - Continuing to use Puppet 5
- Things to watch out for
  - `Sensitive`
  - `Deferred`
- Basics of how to use it with a simple example flow that a user could reproduce

**Comment by sgnn7** [comment]
Internal artifact shared on Slack.Moving to "review" column.

**Comment by sgnn7** [comment]
Closed via published blog [here](https://www.conjur.org/blog/puppet-secrets-management-key-conjur-v3-enhancements/).
