### ISSUE TITLE
Puppet Forge Download Broken Through Artifactory for Version 3.0.0-rc2 and rc3

### ISSUE THREAD

**Issue by frankmundt** [cyberark/conjur-puppet#220]
## Using Artifactory to access the Puppet Forge - it fails downloading. 
We are getting the error "'cyberark-conjur-3.0.0-rc3' is not a valid release slug' from Puppet via Artifactory. 

We are using Artifactory 6.5.2 and Puppet Enterprise 2019.5

curl https://artifactory.localhost/artifactory/api/puppet/puppet_virtual_repo/v3/releases/cyberark-conjur-3.0.0-rc3. 

Version 3.0.0-rc2 also fails with the same error - but version 2.0.6 works fine.

**Comment by izgeri** [comment]
@frankmundt it looks like this is a known issue in Artifactory, and they have a fix available in Artifactory 7.7.0.

We are aiming to publish v3.0.0 within the next week or so (see #219 to watch for updates), which will hopefully resolve this for you.

**Comment by frankmundt** [comment]
Apologies for making you research my issue.  I will be watching for v3.0.0, thanks!

**Comment by izgeri** [comment]
No worries @frankmundt. Since there's nothing for our project to do on this (besides release v3.0.0), I'll close this issue now.
