### ISSUE TITLE
Running examples/puppetmaster test locally results in unknown function error

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-puppet#222]
## Summary
Running the examples/puppetmaster/test.sh script locally results in the following error:
```
Error: Failed to apply catalog: Unknown function 'conjur::secret'
```

## Steps to Reproduce
1. Change directory to examples/puppetmaster
2. Set the following environment variables:
```
$ export CLEAN_UP_ON_EXIT=false
$ export INSTALL_PACKAGED_MODULE=false
$ export COMPOSE_PROJECT_NAME=puppetmaster_manual
```
3. Run the test script:
```
./test.sh
```

## Expected Results
Test script should pass, and the last line displayed should be:
```
ALL TESTS COMPLETED
```

## Actual Results (including error logs, if applicable)
Running test results in error shown in the `Summary` section above.

## Reproducible
   * [ ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

**Comment by sgnn7** [comment]
Closed via https://github.com/cyberark/conjur-puppet/pull/223
