### ISSUE TITLE
Module supports a variety of common Operating Systems

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-puppet#23]
As an administrator, I want the module to support a variety of operating systems, so that I am confident it will work for the operating systems within my environment.

GIVEN this module
WHEN the test suite is run
THEN module functionality is validated on the below operating systems <sup>1</sup>

<sup>1</sup> Supported operating systems:
- Windows
- Red Hat 7
- CentOS 7
- Ubuntu 18.04 LTS
- Debian 9

**Comment by izgeri** [comment]
Note: until today, we were testing against ubuntu, centos, and debian. Unfortunately the centos and debian images were removed from dockerhub, so as of [this PR](https://github.com/cyberark/conjur-puppet/pull/85/files) we are now testing against ubuntu and alpine.

As part of #20, I will be filing separate issues for adding automation for running this integration on windows. As such, I am closing this issue now.
