### ISSUE TITLE
Release v3.1.0

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#240]
## Is your feature request related to a problem? Please describe.

This issue is created to track the release of v3.1.0

## Describe the solution you would like

AC:

- [x] v3.1.0 is the new version in metadata
- [x] README lists project as Certified
- [x] Any references to Trusted certification level are removed
- [x] v3.1.0 has a tag in the changelog
- [x] v3.1.0 is available on Puppet Forge
- [ ] v3.1.0 is available on our releases page

**Comment by izgeri** [comment]
v3.1.0 should also be updated so that:
- README lists project as `Certified`
- any references to `Trusted` certification level can be removed

**Comment by sgnn7** [comment]
Reopening this - we still haven't published the artifacts yet nor tagged
