### ISSUE TITLE
Integration CI tests are executed in Linux and Windows environments

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-puppet#27]
The existing smoke tests should be executed in both linux environments (RedHat, Ubuntu, etc.) and Windows environments (2008R2 through 2019, including core version).

Currently these are only run on linux within docker containers.

**Comment by jvanderhoof** [comment]
After running into a challenges reliably automating these tests through Jenkins, we're pausing the effort.  This effort yielded manual tests which will be used in the future.
