### ISSUE TITLE
Smoke tests include Conjur OSS

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-puppet#36]
As an open source Puppet/Conjur user, I want to be assured the Puppet module works for Conjur OS, so that I don't get frustrated.

WHEN smoke tests run
THEN they are run against both Conjur Enterprise (DAP), and Conjur OS

**Developer Notes**
Initial PR for adding smoke tests on Windows: https://github.com/cyberark/conjur-puppet/pull/33/files

**Comment by garkler** [comment]
As per discussion with @jvanderhoof and @boazmichaely , we have sufficient testing at this point and we will move this card to the icebox

**Comment by jvanderhoof** [comment]
We're putting this on the back-burner to focus on more pressing work.

**Comment by sgnn7** [comment]
OSS is now a first-class citizen in smoketests/E2E tests. Closing.
