### ISSUE TITLE
Puppet CA chain retrieval doesn't rely on internal Puppet API methods

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-puppet#44]
On Puppet 6, the Conjur module reports the error:
```
undefined method `ssl_configuration' for #<Puppet::SSL::Validator::DefaultValidator:0x00000000069b2778>
```

This comes from https://github.com/cyberark/conjur-puppet/blob/353c3e2ec45ee1f97324493fd8145146c921d35d/lib/facter/conjur.rb#L75 where we use the internal Puppet API to retrieve the Puppet CA chain.

This instance method existed in [Puppet 5](https://www.rubydoc.info/gems/puppet/5.0.0/Puppet/SSL/Validator/DefaultValidator) but was removed in [Puppet 6](https://www.rubydoc.info/gems/puppet/Puppet/SSL/Validator/DefaultValidator).

**Comment by sgnn7** [comment]
iIn puppet it looks like even getting the master server cert is fragile to the max - we assume that if the indirector is not `:compiler` we use methods only available in `:rest` indirector even though there’s like 16 different types.

I think we may need to figure out different asymmetric key data to encrypt the token with between agent and master

Logic flow:
https://github.com/cyberark/conjur-puppet/blob/v2.0.3/lib/facter/conjur.rb#L86-L89
```
    def standalone?
      # HACK is there a better way to detect if this is puppet apply?
      Puppet[:catalog_terminus] == :compiler
    end

    begin
        ...
        if standalone?
          config['token'] = token
        else
          config['encrypted_token'] = encrypt_for_master token
        end
      end
```

Use of rest-only methods (https://github.com/cyberark/conjur-puppet/blob/v2.0.3/lib/facter/conjur.rb#L73-L74):
```
    def puppet_certificate
      @puppet_certificate ||= begin
        itc = Puppet::Resource::Catalog.indirection.terminus.class
        get_ssl_cert itc.server, itc.port,
            Puppet::SSL::Validator.default_validator.ssl_configuration.ca_chain_file
      end
    end
```

Here, `itc.server` and `itc.port` are only available to [REST indirector](https://github.com/puppetlabs/puppet/blob/ba4d1a1aba0095d3c70b98fea5c67434a4876a61/lib/puppet/indirector/rest.rb#L55-L102)

**Comment by sgnn7** [comment]
[`Puppet:Util::Connection`](https://www.rubydoc.info/gems/puppet/Puppet/Util/Connection) seemed promising but it's for querying the server settings (which are unavailable on the agent)
