### ISSUE TITLE
Failing build is fixed

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#50]
The [failing build](https://jenkins.conjur.net/job/cyberark--conjur-puppet/job/master/444/) needs to be investigated and fixed.

**Comment by JakeQuilty** [comment]
scenario2 is the only scenario that is failing. When I echo out host_factory_token after local host_factory_token=$(runInConjur jq -r '.[].token' hftoken.json | tr -d '\r') in the smoketest.sh(the test that's failing) I get OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"jq\": executable file not found in $PATH": unknown . That is the only command in the script that asks the cli container to use the jq command.

**Comment by JakeQuilty** [comment]
Adding `runInConjur apt-get install jq` to the script before the jq command makes it pass the tests

**Comment by JakeQuilty** [comment]
Made PR https://github.com/cyberark/conjur-cli/pull/254
