### ISSUE TITLE
Conjur passwords are updated in test suite

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#51]
There are a couple of example Conjur containers that are spun up that use `CONJUR_ADMIN_PASSWORD` with value `admin`. These should be updated to use something more complex, like `ADmin123!!!!`

AC:
- `examples/puppetmaster/docker-compose.yml` is updated to use a more complex Conjur admin password
- `examples/docker-compose.yml` is updated to use a more complex admin password
- All examples still work as expected with the updates

**Comment by JakeQuilty** [comment]
Updated: 
`conjur-puppet/examples/ee/docker-compose.yml`
`conjur-puppet/examples/docker-compose.yml`
`conjur-puppet/examples/puppetmaster/docker-compose.yml`
