### ISSUE TITLE
Jenkins builds fail for conjur-puppet master branch for Conjur V5

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-puppet#61]
## Summary
The Jenkins builds for the conjur-puppet master branch are failing in the Conjur V5 test scenarios:
https://jenkins.conjur.net/job/cyberark--conjur-puppet/job/master/

This is a recent breakage, starting at 3/15, and failures are consistent.

Failures appear to revolve around line 36 in manifests/init.pp:
```
Evaluation Error: Error while evaluating a Method call, Unauthorized (file: /src/conjur/manifests/init.pp, line: 36, column: 35) on node f9dbff1fc804.ec2.internal[0m
```
and later:
```
13:45:48  [1;33mWarning: Unknown variable: 'api_key'. (file: /src/conjur/manifests/init.pp, line: 36, column: 50)[0m
13:45:48  [1;33mWarning: Unknown variable: 'authn_account'. (file: /src/conjur/manifests/init.pp, line: 36, column: 60)[0m
13:45:48  [1;31mError: Evaluation Error: Error while evaluating a Method call, 'conjur::token' parameter 'login' expects a String value, got Undef (file: /src/conjur/manifests/init.pp, line: 36, column: 35) on node d2dc3441b013.ec2.internal[0m
```

## Steps to Reproduce
Run the Jenkins tests for cyberark/conjur-puppet

## Expected Results
Consistently passing Jenkins tests.

## Actual Results (including error logs, if applicable)
Failures in the Conjur V5 test scenario.

## Additional Information
There were many changes made recently to cyberark/conjur yesterday, so perhaps conjur-puppet needs changes to sync up?

**Comment by sgnn7** [comment]
Fixed by #63
