### ISSUE TITLE
Add windows tests for build pipeline

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-puppet#69]
## Is your feature request related to a problem? Please describe.

We don't have automated tests for Windows platforms so we should add those in to ensure we don't push a broken build.

## Describe the solution you would like

AC:
- [ ] Automated builds also test the windows platform

**Comment by micahlee** [comment]
Just a note that we had a large effort to get this working with Windows executors on Jenkins. This was de-prioritized and forgotten, but much of work is still present in this branch: https://github.com/cyberark/conjur-puppet/tree/windows-executor

**Comment by micahlee** [comment]
There was another separate integration tests effort at the same time that use terraform to create windows resources in AWS that tested the puppet module: https://github.com/cyberark/conjur-puppet/compare/27-integration-tests
