### ISSUE TITLE
Manual test multiple API keys can serve different roles

### ISSUE THREAD

**Issue by Tovli** [cyberark/conjur-puppet#83]
We want to verify that a customer can work with API key per role and that each API key is served to the right node based on its role

This will be done for Puppet 5 on Linux. Further versions and OS might be tested on future issues

DoD
- [x] Puppet can get secrets for nodes and use the relevant API key based on their role

**Comment by eranha** [comment]
Puppet Version 5
**Configure hostname**
Server:
  Change the server host name to the FQDN of the server in /etc/hostname
  Add [server-ip] puppet-server to hosts file in /etc/hosts
node:
  Change the host name to the puppet-agent of the server in /etc/hostname
  add [server-ip] puppet-server to /etc/hosts

**Install Puppet**
wget https://apt.puppetlabs.com/puppet5-release-xenial.deb


`sudo dpkg -i puppet5-release-xenial.deb
sudo apt-get update -y`

**Install Server**
`sudo apt-get install puppetserver -y`

After installing the Puppet server, you will need to configure the memory allocation. You are recommended to customize the memory usage depends on how much memory your master node has. You can do this by editing /etc/default/puppetserver file:
`sudo nano /etc/default/puppetserver`
Change the lines as per your server capacity:
From
`JAVA_ARGS="-Xms2g -Xmx2g -XX:MaxPermSize=256m"`
To
`JAVA_ARGS="-Xms512m -Xmx512m"`

Save and close the file, then start Puppet server and enable it to start on boot time with the following command:
`sudo systemctl start puppetserver
sudo systemctl enable puppetserver`

You can check the status of the Puppet server using the following command:
`sudo systemctl status puppetserver`

**Install Puppet Agent**

sudo apt-get install puppet-agent -y
sudo nano /etc/puppetlabs/puppet/puppet.conf
Add the following lines:
[main]
certname = puppet-agent
server = server-fqdn
environment = production

**Start Puppet**
`sudo systemctl start puppet
sudo systemctl enable puppet`

**Sign Node Certificate**
on puppet-server run 
`sudo /opt/puppetlabs/bin/puppet cert list`

You should see the one request with your agent node’s hostname:
`"puppet-agent" (SHA256) 7C:28:E8:AF:09:23:55:19:AF:C1:EE:C3:66:F2:02:73:AD:7F:53:17:28:CE:B0:26:AE:C7:6C:67:16:05:6F:2E`


Next, sign a certificate request using the following command:
sudo /opt/puppetlabs/bin/puppet cert sign puppet-agent
You should see the following output:
`Signing Certificate Request for:
"puppet-agent" (SHA256) 7C:28:E8:AF:09:23:55:19:AF:C1:EE:C3:66:F2:02:73:AD:7F:53:17:28:CE:B0:26:AE:C7:6C:67:16:05:6F:2E
Notice: Signed certificate request for puppet-agent
Notice: Removing file Puppet::SSL::CertificateRequest puppet-agent at '/etc/puppetlabs/puppet/ssl/ca/requests/puppet-agent.pem'`


The Puppet Master server is now able to communicate and control the Agent node. If you want to sign certificate request of multiple nodes at once, then run the following command:
`sudo /opt/puppetlabs/bin/puppet cert sign --all`

**Comment by Tovli** [comment]
@cyberark/palmtree 
Please lmk if you got notification due to this mention
