### ISSUE TITLE
Manually verify that the Conjur Puppet plugin works in Windows with Puppet v5

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#86]
## Overview
We don't have automated tests for this Puppet integration with Windows, so we should manually verify that it works with Puppet v5.

In this card, we'd like to:
- Validate that this integration works in a Windows environment (using Windows server 2012 or 2016) when used with Puppet v5
- Document the process to get a test environment working, so that other developers can also create a Windows development environment

## Definition of Done

Test environment:
- Windows Server 2012 or 2016
- Puppet v5 (clients and server)
- Conjur or DAP (either way is fine - just document what you used) configured with a single [Conjur host identity](https://github.com/cyberark/conjur-puppet/#conjur-host-identity-with-api-key) for the Puppet master server and nodes
- The [latest release](https://github.com/cyberark/conjur-puppet/releases/tag/v2.0.3) of our Puppet integration

Using this environment, validate that you can run through a scenario like the [smoketest example](https://github.com/cyberark/conjur-puppet/blob/master/examples/scenario1.pp) - ie that you can configure Puppet with a Conjur host and API key and successfully use Puppet to retrieve a secret value.

_If you cannot_, document the errors that you see along the way and any suggestions / ideas you have for how to address them (if any).

AC:
- [ ] There are notes on this issue about how the test environment was created, so that others may try to follow the same instructions and try to reproduce
- [ ] There are notes on this issue about any errors encountered when running through the scenario outlined above

**Comment by izgeri** [comment]
Note: this is a potential bug you may run into: #47

**Comment by izgeri** [comment]
Note: if you are able to install puppet on a windows machine in AWS, maybe we could take a snapshot of that machine when it's clean and configured so that the team can reuse the snapshot to stand up new instances?

**Comment by diverdane** [comment]
I've confirmed that the unreleased conjur-puppet works on a v5 windows puppet agent talking to a v5 puppet server, using pre-provisioned machine identity via regedit and windows credential manager.

# Setup Overview

- Mac host
- Puppet server running via docker-compose (examples/puppetmaster/smoketest_e2e.sh)
- Windows VM created via Vagrant (see https://github.com/cyberark/conjur-puppet/pull/94)

# conjur-puppet Module
The conjur-puppet module is based on this commit https://github.com/cyberark/conjur-puppet/commit/115c990edbd0615c22312bc6a236453db63de53c.

# Puppet Server

- V5 Puppet server (version: 5.3.7)
- The setup is based on examples/puppetmaster/smoketest_e2e.sh, modified to:
   - Don't do cleanup after testing Linux agents
   - Expose Conjur on host port 30301
   - Expose Puppet on host port 30302
   - In Puppet server container, add /etc/hosts entry `<docker-gateway-ip> conjur`

# Puppet Agent

- V5 Puppet agent (version: 5.5.8)
- Pre-provisioned machine identity using regedit and windows credentials manager
   This is configured by running the following from the `vagrant/windows2016_puppet`
    directory:
```
        vagrant powershell -c /vagrant/clean_puppet_certs.ps1
        vagrant powershell -c /vagrant/del_etc_hosts_conjur.ps1
        vagrant powershell -c /vagrant/del_etc_hosts_puppet.ps1
        vagrant powershell -c /vagrant/add_etc_hosts.ps1
        vagrant powershell -c /vagrant/add_registry_conjur.ps1
        vagrant powershell -c /vagrant/add_cred_conjur.ps1.  ### Modify with rotated api key for host/node01
```
