### ISSUE TITLE
There has been a security review of Puppet v6 support for Windows

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#87]
See "Milestone 1" in #20

**Comment by izgeri** [comment]
Initial questions that came out of security review (**note: answers will not be added here**):
- [ ] Investigate whether a limited user can get to the identity files written to disk in the node
- [ ] Investigate further how Puppet handles its sensitive data type - is there any caching here that might leave something vulnerable?
- [ ] Investigate whether Puppet has any auditing/monitoring we need to be concerned about around its secret handling
- [ ] Add warnings to the Puppet module if it detects it's using HTTP to talk to Conjur and not HTTPS
- [ ] Add warning to docs about standalone Puppet server since we don't have a cert to do encryption we would otherwise do in that case

**Comment by diverdane** [comment]
A security review was conducted. The following takeaways/action items were identified:

1. Issue #1: Add documentation indicating that on Windows nodes, access to the Conjur connection information in the Windows registry must be disabled for non-administrator users. This can be done using the regedit.exe utility. Below is a snapshot for how access can be disabled for the conjur registry settings for non-administrator users.
2. Issue #1: Add documentation indicating that the file permissions for these files: /etc/conjur.conf, /etc/conjur.identity must be set to 600.
3. Issue #4: File a cyberark/conjur-puppet repo issue: Add Warnings or Fail When HTTP Used Between Puppet Module and Conjur.
4. Issue #5: File an cyberark/conjur-puppet repo issue: Add Warning to Docs About Lack of Encryption for Standalone Puppet Server.

**Comment by izgeri** [comment]
Issues that were filed to follow up from the security review:
1. #142 - Include warning to disable `Users` write access to WinReg entries for Conjur
2. #143 - Include warning to set Conjur identity files permissions to `600`
3. #144 - Add warnings to the Puppet module if HTTPS not being used to talk to Conjur
4. #145 - Include warning that stand-alone Puppet (Puppet Apply) does not provide encryption
