### ISSUE TITLE
The difference between Puppet open source and Puppet Enterprise is understood

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#88]
In order to understand whether our automated test suite / our manual tests need to test against Puppet Enterprise, we need to better understand the difference between Puppet OSS and Puppet Enterprise as it relates to our integration and the functionality it requires.

In this spike, we will research the difference between the two products and document in this card any info that is or may be relevant. This effort should be timeboxed to no more than a couple of hours.

AC:
- [ ] This card has notes on the differences between Puppet open source and Puppet Enterprise and what differences may be relevant to our integration. In particular, if possible this issue should result in a recommendation about whether or not we will need to (manually or automatically) add tests that work with Puppet enterprise.

**Comment by izgeri** [comment]
https://puppet.com/products/puppet-enterprise/open-source-comparison/#compare

**Comment by doodlesbykumbi** [comment]
In my research I came across the PDK which is the standard tooling for develop modules. It comes with a validation and testing framework, see https://puppet.com/docs/pdk/1.x/pdk_overview.html. There's a facility to convert non-PDK modules into PDK. 

In my research I learnt the following...
+ Puppet Enterprise is built on top of the OS offering. 
+ There exist enterprise only modules but that seem to be an exclusivity consideration more than anything.
+ In the documentation for module development (https://puppet.com/docs/pdk/1.x/pdk_testing.html) I found:
> To ensure that your module works with Puppet, validate and unit test your modules against specific versions of Puppet and Puppet Enterprise.
+ There is a concept of “Puppet Supported Modules” and there’s mention of them being tested on Puppet Enterprise, see https://forge.puppet.com/supported?_ga=2.232476319.1469263667.1594626844-275758387.1593088824#testing-section.

It seems that testing modules on enterprise (separate from OSS) is generally a good idea. I'm still not sure why... I haven't found much detail about that. I wondered if it might be worth reaching out to Puppet.

**Comment by izgeri** [comment]
@doodlesbykumbi I've asked BizDev if they can help us get more info from Puppet on this - I'll let you know what I hear back.

**Comment by izgeri** [comment]
Note: we heard the following back from Puppet, which seems to indicate testing against Puppet Enterprise will not be required:
> Within the context of a Puppet module as the vehicle for integration, Puppet Enterprise and OSS are identical. The language, fact, function, type, and provider api are all entirely the same between the free and paid-for releases. The proprietary components of PE are disaster recovery and failover, the console ui, an optional performant communication backend for Bolt, the installer, and CD4PE, which handles orchestrating the process of testing modules and their impact on the infrastructure before deployment.
