### ISSUE TITLE
Support for Puppet 6 with Windows nodes has been manually tested

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#89]
Manual tests to run through:

## Puppet 5 tests
- [ ] Conjur identity via host factory, configured in Hiera, Windows Server 2019
- [ ] Conjur identity via host factory, configuration hardcoded in manifest, Windows Server 2016
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows Server 2012 R2
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows 2016
- [ ] Conjur identity via host / API key, configuration in Hiera, Windows Server 2012 R2
- [ ] Conjur identity via host / API key, configuration hardcoded in manifest, Windows Server 2019

## Puppet 6 tests
- [ ] Conjur identity via host factory, configuration hardcoded in manifest, Windows 2012 R2
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows 2019
- [ ] Conjur identity via host / API key, configuration in Hiera, Windows 2016

In all tests, we are validating that if the server manifest includes conjur configuration and invokes lookup plugin, that it correctly sends the secret values back to the agent, i.e. we need to verify that the server can authenticate to Conjur and retrieve secrets / pass the values to agent.

**Comment by andytinkham** [comment]
As a note so we remember, I generated the above list by putting this model into [web PICT](http://amibugshare.com/pict/):
`Identity: Host factory, Host/API key
Config: Windows Registry/WinCred, Identity files
Windows Version: Windows 2012, Windows 2016
Puppet version: Puppet 5, Puppet 6`

It then generated the above 5 scenarios to ensure all possible pairs of values are covered.

**Comment by izgeri** [comment]
@sgnn7 @doodlesbykumbi how does this sound as a way to split the cases?

---

@sgnn7 will do:

## Puppet 5 tests
- [ ] Conjur identity via host factory, configuration hardcoded in manifest, Windows Server 2016
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows 2016
- [ ] Conjur identity via host / API key, configuration in Hiera, Windows Server 2012 R2

## Puppet 6 tests
- [ ] Conjur identity via host factory, configuration hardcoded in manifest, Windows 2012 R2
- [ ] Conjur identity via host / API key, configuration in Hiera, Windows 2016

---

@doodlesbykumbi will do:

## Puppet 5 tests
- [ ] Conjur identity via host factory, configured in Hiera, Windows Server 2019
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows Server 2012 R2
- [ ] Conjur identity via host / API key, configuration hardcoded in manifest, Windows Server 2019


## Puppet 6 tests
- [ ] Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows 2019

**Comment by doodlesbykumbi** [comment]
I managed to get through 3 cases using 2019 windows containers. The puppet 6 test for `Conjur identity via host / API key, configuration in Windows Registry / WinCred, Windows 2019` failed as a result of faulty instructions in the README.md. I have a PR to resolve this https://github.com/cyberark/conjur-puppet/pull/140.

**Comment by izgeri** [comment]
Issues that came out of this round of manual testing:
- #147 - When using Puppet server-side credentials, specifying both `cert_file` and `ssl_certificate` errors out on Windows
- PR #140 - Update windows cred example in README.md 


Unknown issue numbers: (@sgnn7 can you please add issue links later?)
- `Warning: Agentâ€™s registry did not contain path Software\CyberArk\Conjur. If this is the`
  `first time using HFTs on this node, this is expected behavior`. This appliest to both HFTs _and_ Hiera
  configs so we need to reword this message. We may want to bump it down to a "Notice" as well
  if we don't expect agent direct config to be used more often than not.
- In docs, examples of `cert_path` for Windows need to use `C:\`-prefixed paths since only PowerShell
  natively resolves paths like `/tmp/foo.pem`.
- In docs, examples of `cert_path` should use a path (e.g `C:\vagrant\.tmp\conjur_ca.pem`, not a "file" function
  `file('C:\vagrant\.tmp\conjur_ca.pem')`.
- `cert_file` examples and definiton **must** include where this path applies to. Specifically, anything that
  doesn't use wincred/registry on the agent implies that this path is on the server which isn't clear in the
  docs at all.

**Comment by sgnn7** [comment]
@izgeri updated

**Comment by izgeri** [comment]
thanks @sgnn7! closing this issue now.
