### ISSUE TITLE
There is a local development environment for Puppet with Windows agents

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#95]

**Comment by izgeri** [comment]
@diverdane please add more info to this card - both about the "definition of done" for the env you are creating and any notes you have (including branch links) for what you've done so far. thanks!

**Comment by diverdane** [comment]
I have a Vagrant/VirtualBox-based option for local development, tested with Windows2016. I should be able to map this to a Windows2012 VM fairly easily. @doodlesbykumbi is working on another option that is based on spinning up containers on an AWS Windows VM.

# Setup Overview

- Mac host
- Puppet server running locally via docker-compose (using examples/puppetmaster/smoketest_e2e.sh)
- Windows VM created via Vagrant (see https://github.com/cyberark/conjur-puppet/pull/94)
   running Puppet Agent
    - Windows configuration can be done remotely from the Mac via `vagrant powershell -c <command>`.
    - Puppet Agent can be installed/replaced dynamically, so devs should be able to keep a long-standing
       "vanilla" Windows VM (powered down when not in use), and install/replace Puppet agent as needed.

# Puppet Server

- V5 Puppet server (version: 5.3.7)
- The setup is based on examples/puppetmaster/smoketest_e2e.sh, modified to:
   - Don't do cleanup after testing Linux agents
   - Expose Conjur on host port 30301
   - Expose Puppet on host port 30302
   - In Puppet server container, add /etc/hosts entry `<docker-gateway-ip> conjur`

# Puppet Agent

- V5 Puppet agent (version: 5.5.8)
- Pre-provisioned machine identity using regedit and windows credentials manager
   This is configured by running the following from the `vagrant/windows2016_puppet`
    directory:
```
        vagrant powershell -c /vagrant/clean_puppet_certs.ps1
        vagrant powershell -c /vagrant/del_etc_hosts_conjur.ps1
        vagrant powershell -c /vagrant/del_etc_hosts_puppet.ps1
        vagrant powershell -c /vagrant/add_etc_hosts.ps1
        vagrant powershell -c /vagrant/add_registry_conjur.ps1
        vagrant powershell -c /vagrant/add_cred_conjur.ps1  ### Modify with rotated api key for host/node01
```
