### ISSUE TITLE
Clean up the README to remove old "conjurize" references

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#97]
AC:
- [ ] Remove the [section](https://github.com/cyberark/conjur-puppet/#pre-established-host-identity) on using `conjurize` (and announce its deprecation in the CHANGELOG) since this is not documented for Conjur OSS / DAP
- [ ] Move the [pre-established host identity on windows](https://github.com/cyberark/conjur-puppet/#pre-establish-host-identity-on-windows-hosts) section under [conjur host identity with API key](https://github.com/cyberark/conjur-puppet/#pre-establish-host-identity-on-windows-hosts) as a new Windows-focused subsection, since what it's really covering is using the host/API key method in Windows

**Comment by izgeri** [comment]
@alexkalish can you please confirm that removing the reference to `conjurize` is ok here? the alternative is adding a big `Conjur Enterprise v4 only` caveat to this section and then removing it when we deprecate v4 support

I'd also appreciate your feedback on whether the next tag can announce deprecation for Conjur v4 support, to be removed in a soon-to-be-tagged future version.

**Comment by alexkalish** [comment]
@sgnn7, @izgeri: Looks like the 🚢 may have already sailed, but I think that we should just put this identity method behind a big "v4 ONLY" stipulation.  We aren't removing this feature from v4; we just are not supporting it moving forward.

Regarding v4, our plan is to not support this version with Puppet module v3.  So are you asking if we can declare that deprecation now?

**Comment by izgeri** [comment]
@alexkalish it's not hard to add it back with the big caveat; I can do that now, with plans to remove it when we actually deprecate v4

and yes, I'd like to announce the deprecation in the next tag if we can, to be actually removed in the following version.
