### ISSUE TITLE
Update README to have clear and correct documentation on usage with Windows agents

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#98]
At current, the documentation only has [one section](https://github.com/cyberark/conjur-puppet/#pre-establish-host-identity-on-windows-hosts) on using this integration with Windows agents (and it requires using the host/API key flow)

AC:
- [ ] The docs are clear about which use cases are supported for Windows agents
- [ ] Based on our experience running Puppet with Windows agents using our plugin, any additional helpful information about using our plugin with Windows is also documented
- [ ] If any documented flows are not supported in Windows, this is clearly indicated in those sections.

**Comment by doodlesbykumbi** [comment]
After testing the flows, I think we support the same things for Linux as we do for Windows, which I think the latest README from your branch communicates well.

> Based on our experience running Puppet with Windows agents using our plugin, any additional helpful information about using our plugin with Windows is also documented
The only difference is regedit + windows credentials manager (vs /etc/conjur.conf and /etc/conjur.identity for Linux). This is already captured. It might be useful to mention the equivalence which might help users reason about machine identity by analogy.

> If any documented flows are not supported in Windows, this is clearly indicated in those sections.
I'm not aware of any flows that are not supported.
